# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dluna-lo <dluna-lo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/19 11:34:29 by dluna-lo          #+#    #+#              #
#    Updated: 2023/05/19 19:00:46 by dluna-lo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= btc
CC 		= c++
CFLAGS	= -Wall -Wextra -Werror -std=c++98
AUTHOR	= dluna-lo


SRCS	= src/main.cpp src/BitcoinExchange.cpp

OBJDIR	=	bin/
